SELECT * FROM CUSTOMERS;
UPDATE CUSTOMERS SET COUNTRY = "TÜRKİYE", AGE = (YEAR(CURDATE()) - YEAR(`BIRTHDATE`));
SELECT CURDATE();
 

 
SELECT DATEDIFF('2024-04-29' , '1964-05-12') AS YEAR;

DELETE FROM CUSTOMERS;
SELECT * FROM CUSTOMERS;