SELECT * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS WHERE ID = 1;
SELECT * FROM CUSTOMERS WHERE `BIRTHDATE` < "1920-10-25";
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE "%ÇAM";
SELECT * FROM CUSTOMERS WHERE TOWN = 445;