SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME;
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME DESC;
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME, GENDER ASC, AGE DESC;
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME, GENDER, AGE DESC;